// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type APIKey struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	ExpireAt int    `json:"expireAt"`
}

type ChangePasswordInput struct {
	Password    string `json:"password"`
	NewPassword string `json:"newPassword"`
}

type NextOptions struct {
	MachineID      *string `json:"machineId"`
	PreviousPassed *bool   `json:"previousPassed"`
}

type Pagination struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type Project struct {
	ProjectName   string     `json:"projectName"`
	LatestSession *string    `json:"latestSession"`
	Sessions      []*Session `json:"sessions"`
	TotalSessions int        `json:"totalSessions"`
}

type Session struct {
	ID      string  `json:"id"`
	Start   int     `json:"start"`
	End     int     `json:"end"`
	Backlog []*Spec `json:"backlog"`
}

type SessionInfo struct {
	ProjectName string `json:"projectName"`
	SessionID   string `json:"sessionId"`
}

type SessionInput struct {
	ProjectName string      `json:"projectName"`
	SpecFiles   []*SpecFile `json:"specFiles"`
}

type Spec struct {
	File              string `json:"file"`
	EstimatedDuration int    `json:"estimatedDuration"`
	Start             int    `json:"start"`
	End               int    `json:"end"`
	Passed            bool   `json:"passed"`
	AssignedTo        string `json:"assignedTo"`
}

type SpecFile struct {
	Tests    []string `json:"tests"`
	FilePath string   `json:"filePath"`
}

type User struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
